name: Tests

on:
  push:
    branches: ["main"]
    paths:
      - '.github/**'
      - 'src/**'
  pull_request:
    branches: ["main"]
    paths:
      - '.github/**'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      # Test reporting based on: https://rakesh-suryawanshi.medium.com/unit-testing-report-with-github-actions-7216f340044e
      - name: Test
        run: dotnet test src/Sample/Sample.Tests/Sample.Tests.csproj --logger "trx;LogFileName=test-results.trx" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
